// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoeCommerce;

#nullable disable

namespace ProyectoeCommerce.Migrations
{
    [DbContext(typeof(eCommerceContext))]
    [Migration("20250113231216_add-hashed-passwpords-in-seeds-5")]
    partial class addhashedpasswpordsinseeds5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Laptop moderna y rápida",
                            Nombre = "Laptop",
                            Precio = 800.99000000000001
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Teléfono inteligente con gran cámara",
                            Nombre = "Smartphone",
                            Precio = 600.49000000000001
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Audífonos inalámbricos",
                            Nombre = "Audífonos",
                            Precio = 150.0
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Monitor 4K UHD",
                            Nombre = "Monitor",
                            Precio = 300.75
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Teclado para gamers",
                            Nombre = "Teclado Mecánico",
                            Precio = 120.5
                        });
                });

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin1@example.com",
                            Nombre = "Admin User 1",
                            NumeroTelefono = "1234567890",
                            Password = "AQAAAAIAAYagAAAAEHjAWkN+Y7Q1oce4X8NtZAUwKU4aNWVPuyMMmtvZzlP76vdZGQfmD6k/lC/h5t61Uw==",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "admin2@example.com",
                            Nombre = "Admin User 2",
                            NumeroTelefono = "1234567891",
                            Password = "AQAAAAIAAYagAAAAENOixQmbDMm4i3SWt/rrymBid0PzUNf0TrpYYLxQ+GxNbeBSU86IP7KredW0lxnU6Q==",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Email = "testuser1@example.com",
                            Nombre = "Test User 1",
                            NumeroTelefono = "1234567892",
                            Password = "AQAAAAIAAYagAAAAEPRKFHl6v++8Jsyg6ylYJC4m9a+cmWd1ytIygwHn/tmGJuQscItnWtGu4UnlET9LtA==",
                            Role = "User"
                        },
                        new
                        {
                            Id = 4,
                            Email = "testuser2@example.com",
                            Nombre = "Test User 2",
                            NumeroTelefono = "1234567893",
                            Password = "AQAAAAIAAYagAAAAEA4ipEs/fQkPzPaSU1xNuDWQ0YEOnqTnU6ZOBlcbQwi9Pskh38gfM785plmnvTGngw==",
                            Role = "User"
                        },
                        new
                        {
                            Id = 5,
                            Email = "testuser3@example.com",
                            Nombre = "Test User 3",
                            NumeroTelefono = "1234567894",
                            Password = "AQAAAAIAAYagAAAAEBjVcFSOinTo3TpO/9hd1B9ODXEqc/jc0YGVWbfLnwFJBfPXocofGk/aREl6ik5iEA==",
                            Role = "User"
                        },
                        new
                        {
                            Id = 6,
                            Email = "testuser4@example.com",
                            Nombre = "Test User 4",
                            NumeroTelefono = "1234567895",
                            Password = "AQAAAAIAAYagAAAAEObi6MSDNP+62nkN7gwW+Z3mtKEsGaYrwdViqrGV2u4APXTWeZXRakww2Y4DF6JoBg==",
                            Role = "User"
                        },
                        new
                        {
                            Id = 7,
                            Email = "admin3@example.com",
                            Nombre = "Admin User 3",
                            NumeroTelefono = "1234567896",
                            Password = "AQAAAAIAAYagAAAAEDvd5hWUC0Qx91U6XuEoelcTtzsAJn1l7HD5bdiyYBnFBgaILkb6iPrf//8ZooQm3g==",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 8,
                            Email = "testuser5@example.com",
                            Nombre = "Test User 5",
                            NumeroTelefono = "1234567897",
                            Password = "AQAAAAIAAYagAAAAEIEkhPASpAcY437nCZ5aKH0XgQSfIl+H0EtF73D7TNVHGeq+EZTQ2iSEZUCz8GeBcQ==",
                            Role = "User"
                        },
                        new
                        {
                            Id = 9,
                            Email = "testuser6@example.com",
                            Nombre = "Test User 6",
                            NumeroTelefono = "1234567898",
                            Password = "AQAAAAIAAYagAAAAEFnS9sjquuxTzKrGs69HhhNhum3M20M5CsRj4Z5CpBNCJfP+Ixx7+o6rvuaj+dmyJw==",
                            Role = "User"
                        },
                        new
                        {
                            Id = 10,
                            Email = "testuser7@example.com",
                            Nombre = "Test User 7",
                            NumeroTelefono = "1234567899",
                            Password = "AQAAAAIAAYagAAAAECAtE4Ibq1QksEOsI3Ovj9ML+W2da2vP8ZDxIEZIcWl+eZXpQ5SPwVZBnGsQRLX8gw==",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Wishlists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Regalos de Navidad",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Compras de Tecnología",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Hogar",
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Libros Favoritos",
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Deportes",
                            UsuarioId = 5
                        });
                });

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.WishlistProducto", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaProductoAgregado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductoId", "WishlistId");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistProductos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            WishlistId = 1,
                            FechaCreacion = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaProductoAgregado = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laptop para Regalo"
                        },
                        new
                        {
                            ProductoId = 3,
                            WishlistId = 1,
                            FechaCreacion = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaProductoAgregado = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Audífonos para Juan"
                        },
                        new
                        {
                            ProductoId = 2,
                            WishlistId = 2,
                            FechaCreacion = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaProductoAgregado = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Smartphone Moderno"
                        },
                        new
                        {
                            ProductoId = 4,
                            WishlistId = 3,
                            FechaCreacion = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaProductoAgregado = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Monitor para Hogar"
                        },
                        new
                        {
                            ProductoId = 5,
                            WishlistId = 4,
                            FechaCreacion = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaProductoAgregado = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Teclado Mecánico para Gaming"
                        });
                });

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.Wishlist", b =>
                {
                    b.HasOne("ProyectoeCommerce.Models.Entity.Usuario", "Usuario")
                        .WithMany("Wishlists")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.WishlistProducto", b =>
                {
                    b.HasOne("ProyectoeCommerce.Models.Entity.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoeCommerce.Models.Entity.Wishlist", "Wishlist")
                        .WithMany("WishlistProductos")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.Usuario", b =>
                {
                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.Wishlist", b =>
                {
                    b.Navigation("WishlistProductos");
                });
#pragma warning restore 612, 618
        }
    }
}
