// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoeCommerce;

#nullable disable

namespace ProyectoeCommerce.Migrations
{
    [DbContext(typeof(eCommerceContext))]
    [Migration("20250111211717_modify-user-auth")]
    partial class modifyuserauth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Laptop moderna y rápida",
                            Nombre = "Laptop",
                            Precio = 800.99000000000001
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Teléfono inteligente con gran cámara",
                            Nombre = "Smartphone",
                            Precio = 600.49000000000001
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Audífonos inalámbricos",
                            Nombre = "Audífonos",
                            Precio = 150.0
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Monitor 4K UHD",
                            Nombre = "Monitor",
                            Precio = 300.75
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Teclado para gamers",
                            Nombre = "Teclado Mecánico",
                            Precio = 120.5
                        });
                });

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            Nombre = "John Doe",
                            NumeroTelefono = "1234567890",
                            Password = "hashed_password_1",
                            Role = "User"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            Nombre = "Jane Smith",
                            NumeroTelefono = "9876543210",
                            Password = "hashed_password_2",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alice.johnson@example.com",
                            Nombre = "Alice Johnson",
                            NumeroTelefono = "4567891230",
                            Password = "hashed_password_3",
                            Role = "User"
                        },
                        new
                        {
                            Id = 4,
                            Email = "bob.brown@example.com",
                            Nombre = "Bob Brown",
                            NumeroTelefono = "3216549870",
                            Password = "hashed_password_4",
                            Role = "User"
                        },
                        new
                        {
                            Id = 5,
                            Email = "charlie.davis@example.com",
                            Nombre = "Charlie Davis",
                            NumeroTelefono = "6549873210",
                            Password = "hashed_password_5",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Wishlists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Regalos de Navidad",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Compras de Tecnología",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Hogar",
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Libros Favoritos",
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Deportes",
                            UsuarioId = 5
                        });
                });

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.WishlistProducto", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaProductoAgregado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductoId", "WishlistId");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistProductos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            WishlistId = 1,
                            FechaCreacion = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaProductoAgregado = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laptop para Regalo"
                        },
                        new
                        {
                            ProductoId = 3,
                            WishlistId = 1,
                            FechaCreacion = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaProductoAgregado = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Audífonos para Juan"
                        },
                        new
                        {
                            ProductoId = 2,
                            WishlistId = 2,
                            FechaCreacion = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaProductoAgregado = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Smartphone Moderno"
                        },
                        new
                        {
                            ProductoId = 4,
                            WishlistId = 3,
                            FechaCreacion = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaProductoAgregado = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Monitor para Hogar"
                        },
                        new
                        {
                            ProductoId = 5,
                            WishlistId = 4,
                            FechaCreacion = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaProductoAgregado = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Teclado Mecánico para Gaming"
                        });
                });

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.Wishlist", b =>
                {
                    b.HasOne("ProyectoeCommerce.Models.Entity.Usuario", "Usuario")
                        .WithMany("Wishlists")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.WishlistProducto", b =>
                {
                    b.HasOne("ProyectoeCommerce.Models.Entity.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoeCommerce.Models.Entity.Wishlist", "Wishlist")
                        .WithMany("WishlistProductos")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.Usuario", b =>
                {
                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("ProyectoeCommerce.Models.Entity.Wishlist", b =>
                {
                    b.Navigation("WishlistProductos");
                });
#pragma warning restore 612, 618
        }
    }
}
